/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
Author: Pixman (https://sketchfab.com/Pixmani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-medieval-house-54fc5fdb22f8484c940335f99b3c5020
Title: Stylized medieval house
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.polySurface13632_metal_1_0.geometry} material={materials.metal_1} />
        <mesh geometry={nodes.polySurface13632_krysha_1_4_0.geometry} material={materials.krysha_1_4} />
        <mesh geometry={nodes.polySurface13632_listva_6_0.geometry} material={materials.listva_6} />
        <mesh geometry={nodes.polySurface13632_listva_6_0_1.geometry} material={materials.listva_6} />
        <mesh geometry={nodes.polySurface13632_listva_4_0.geometry} material={materials.listva_4} />
        <mesh geometry={nodes.polySurface13632_derevo_8_0.geometry} material={materials.derevo_8} />
        <mesh geometry={nodes.polySurface13632_derevo_5_0.geometry} material={materials.derevo_5} />
        <mesh geometry={nodes.polySurface13632_krysha_1_2_0.geometry} material={materials.krysha_1_2} />
        <mesh geometry={nodes.polySurface13632_krysha_1_1_0.geometry} material={materials.krysha_1_1} />
        <mesh geometry={nodes.polySurface13632_derevo_7_0.geometry} material={materials.derevo_7} />
        <mesh geometry={nodes.polySurface13632_verevka_0.geometry} material={materials.verevka} />
        <mesh geometry={nodes.polySurface13632_flow_9_0.geometry} material={materials.flow_9} />
        <mesh geometry={nodes.polySurface13632_flow_2_0.geometry} material={materials.flow_2} />
        <mesh geometry={nodes.polySurface13632_flow_5_0.geometry} material={materials.flow_5} />
        <mesh geometry={nodes.polySurface13632_metal_2_0.geometry} material={materials.metal_2} />
        <mesh geometry={nodes.polySurface13632_listva_3_0.geometry} material={materials.listva_3} />
        <mesh geometry={nodes.polySurface13632_krysha_1_3_0.geometry} material={materials.krysha_1_3} />
        <mesh geometry={nodes.polySurface13632_derevo_4_0.geometry} material={materials.derevo_4} />
        <mesh geometry={nodes.polySurface13632_derevo_3_0.geometry} material={materials.derevo_3} />
        <mesh geometry={nodes.polySurface13632_kamen_6_0.geometry} material={materials.kamen_6} />
        <mesh geometry={nodes.polySurface13632_derevo_1_0.geometry} material={materials.derevo_1} />
        <mesh geometry={nodes.polySurface13632_metal_3_0.geometry} material={materials.metal_3} />
        <mesh geometry={nodes.polySurface13632_okno_1_0.geometry} material={materials.okno_1} />
        <mesh geometry={nodes.polySurface13632_kamen_5_0.geometry} material={materials.kamen_5} />
        <mesh geometry={nodes.polySurface13632_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface13632_kamen_7_0.geometry} material={materials.kamen_7} />
        <mesh geometry={nodes.polySurface13632_kamen_4_0.geometry} material={materials.kamen_4} />
        <mesh geometry={nodes.polySurface13632_derevo_6_0.geometry} material={materials.derevo_6} />
        <mesh geometry={nodes.polySurface13632_listva_5_0.geometry} material={materials.listva_5} />
        <mesh geometry={nodes.polySurface13632_derevo_2_0.geometry} material={materials.derevo_2} />
        <mesh geometry={nodes.polySurface13632_listva_2_0.geometry} material={materials.listva_2} />
        <mesh geometry={nodes.polySurface13632_derevo_stvol_0.geometry} material={materials.derevo_stvol} />
        <mesh geometry={nodes.polySurface13632_listva_1_0.geometry} material={materials.listva_1} />
        <mesh geometry={nodes.polySurface13632_kamen_2_0.geometry} material={materials.kamen_2} />
        <mesh geometry={nodes.polySurface13632_kamen_3_0.geometry} material={materials.kamen_3} />
        <mesh geometry={nodes.polySurface13632_trava_1_0.geometry} material={materials.trava_1} />
        <mesh geometry={nodes.polySurface13632_zemla_1_0.geometry} material={materials.zemla_1} />
        <mesh geometry={nodes.polySurface13632_zemla_2_0.geometry} material={materials.zemla_2} />
        <mesh geometry={nodes.polySurface13632_black_0.geometry} material={materials.black} />
        <mesh geometry={nodes.polySurface13632_lampa_0.geometry} material={materials.lampa} />
        <mesh geometry={nodes.polySurface13632_dom_stena_1_0.geometry} material={materials.dom_stena_1} />
        <mesh geometry={nodes.polySurface13632_kamen_1_0.geometry} material={materials.kamen_1} />
        <mesh geometry={nodes.polySurface13632_gradka_0.geometry} material={materials.gradka} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
